build:
  environment:
    php:
      version: 8.3.22

  dependencies:
    before:
      - composer install --prefer-dist --no-interaction --no-progress

  tests:
    override:
      - command: vendor/bin/phpunit --coverage-clover=coverage.clover
        coverage:
          file: coverage.clover
          format: clover

filter:
  paths:
    - 'src/*'
    - 'tests/*'

tools:
  php_code_sniffer:
    config:
      standard: PSR2
