build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

checks:
  php: true  # 启用 Scrutinizer PHP 内建分析（包括 Code Rating）

tools:
  php_code_sniffer:
    config:
      standard: PSR2
